# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qt_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pyperclip as cb

class Ui_MainWindow(object):


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(772, 398)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textArea = QtWidgets.QTextEdit(self.centralwidget)
        self.textArea.setGeometry(QtCore.QRect(0, 0, 771, 331))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textArea.setFont(font)
        self.textArea.setObjectName("textArea")
        self.insertEmoji = QtWidgets.QPushButton(self.centralwidget)
        self.insertEmoji.setGeometry(QtCore.QRect(10, 340, 231, 31))
        self.insertEmoji.setObjectName("insertEmoji")
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        self.statusLabel.setGeometry(QtCore.QRect(340, 340, 231, 31))
        self.statusLabel.setObjectName("statusLabel")
        self.copyText = QtWidgets.QPushButton(self.centralwidget)
        self.copyText.setGeometry(QtCore.QRect(530, 340, 231, 31))
        self.copyText.setObjectName("copyText")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.emojis = ['\U0001F621','\U0001F922','\U0001F628','\U0001F600','\U0001F610','\U0001F625','\U0001F632']

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.insertEmoji.clicked.connect(lambda: self.insertEmojiAction(self.captureEmoji()))
        self.copyText.clicked.connect(lambda: self.copyToClipAction(self.textArea.toPlainText()))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.insertEmoji.setText(_translate("MainWindow", "Insert Face Emoji"))
        self.copyText.setText(_translate("MainWindow", "Copy To Clipboard"))

    def insertEmojiAction(self,emoji_idx):
        self.statusLabel.setText("Emoji Inserted")
        text = self.textArea.toPlainText() + self.emojis[emoji_idx] + " "
        self.textArea.setPlainText(text)

    def copyToClipAction(self,text):
        self.statusLabel.setText("Copied Text to Clipboard")
        cb.copy(text)

    def captureEmoji(self):
        curr_emoji = None
        with open('curr_emoji.txt', 'r') as f:
            curr_emoji = f.read()
        #print(emojis[int(curr_emoji)])
        return int(curr_emoji)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
